'use client';

import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import { ArrowRight, MessageSquare, RefreshCw, Star } from 'lucide-react';

import { apiAdmin } from '@/lib/api-client';

type ReviewRow = { id: string; rating: number; comment: string; createdAt: string; user?: { id: string; name: string; email: string; avatar: string } | null; bot?: { id: string; title: string; sellerName: string; sellerId: string } | null };

export default function AdminReviewsPage() {
  const [rows, setRows] = useState<ReviewRow[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { try { setRows(await apiAdmin<ReviewRow[]>('/api/admin/reviews')); } catch (cause) { setRows([]); setError(cause instanceof Error ? cause.message : 'Không tải được reviews.'); } }, []);
  useEffect(() => { void load(); }, [load]);
  return <div className="space-y-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-[#1677ff]">Trust & Safety</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-[#12151b]">Review rủi ro cao</h1><p className="mt-2 text-sm text-[#69707d]">Danh sách này chỉ là tín hiệu cần review, không tự động kết luận gian lận.</p></div><button type="button" onClick={() => void load()} className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-[#dfe3e8] bg-white px-3.5 py-2 text-sm font-semibold text-[#36404d] hover:border-[#1677ff]/40 hover:text-[#1677ff] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1677ff]"><RefreshCw className="h-4 w-4" aria-hidden /> Làm mới</button></div>{error ? <div className="rounded-lg border border-[#f0b4ba] bg-[#fff4f4] px-4 py-3 text-sm text-[#b42332]">{error}</div> : null}<section className="overflow-hidden rounded-xl border border-[#e5e7eb] bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="border-b border-[#edf0f2] bg-[#fbfcfd] text-[11px] font-bold uppercase tracking-[0.08em] text-[#69707d]"><tr><th className="px-5 py-3 sm:px-6">Reviewer</th><th className="px-5 py-3">Bot / Seller</th><th className="px-5 py-3">Rating</th><th className="px-5 py-3">Nội dung</th><th className="px-5 py-3 sm:px-6"><span className="sr-only">Open</span></th></tr></thead><tbody className="divide-y divide-[#edf0f2]">{rows?.map((row) => <tr key={row.id} className="hover:bg-[#fbfcfd]"><td className="px-5 py-4 sm:px-6"><p className="font-semibold text-[#12151b]">{row.user?.name || 'Người dùng'}</p><p className="mt-1 text-xs text-[#69707d]">{row.createdAt}</p></td><td className="px-5 py-4"><p className="max-w-[230px] truncate font-semibold text-[#12151b]">{row.bot?.title || 'Bot không tồn tại'}</p><p className="mt-1 text-xs text-[#69707d]">{row.bot?.sellerName || '—'}</p></td><td className="px-5 py-4"><span className="inline-flex items-center gap-1 rounded-md bg-[#dc3545]/10 px-2 py-1 text-xs font-bold text-[#b42332]"><Star className="h-3.5 w-3.5 fill-current" aria-hidden /> {row.rating}/5</span></td><td className="max-w-[300px] truncate px-5 py-4 text-xs text-[#69707d]">{row.comment || 'Không có nội dung.'}</td><td className="px-5 py-4 text-right sm:px-6"><Link href={row.bot ? `/admin/bots/${encodeURIComponent(row.bot.id)}` : '/admin'} className="inline-flex items-center gap-1.5 font-semibold text-[#1677ff] hover:underline">Kiểm tra <ArrowRight className="h-3.5 w-3.5" aria-hidden /></Link></td></tr>)}</tbody></table></div>{rows?.length === 0 ? <div className="px-6 py-16 text-center"><MessageSquare className="mx-auto h-8 w-8 text-[#8b929d]" aria-hidden /><p className="mt-3 text-sm text-[#69707d]">Chưa có review rating thấp.</p></div> : null}</section></div>;
}
